// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY2bVf6dMNyx3-bOKcuejJ_RHVfFBId_k',
    appId: '1:540960106639:web:34ab8742dffbbaa5d4e8fa',
    messagingSenderId: '540960106639',
    projectId: 'flutter-chat-app-e1f26',
    authDomain: 'flutter-chat-app-e1f26.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e1f26.appspot.com',
    measurementId: 'G-Y54LEXF00G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLB5OcjsKWCpumFc3Evn4PE2ieFxU__k8',
    appId: '1:540960106639:android:f2863ae1c8ce3841d4e8fa',
    messagingSenderId: '540960106639',
    projectId: 'flutter-chat-app-e1f26',
    storageBucket: 'flutter-chat-app-e1f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-dyMEDTvYgUYD-PvmdaIx7ntSTajIbY',
    appId: '1:540960106639:ios:bc14bf18e6a768fbd4e8fa',
    messagingSenderId: '540960106639',
    projectId: 'flutter-chat-app-e1f26',
    storageBucket: 'flutter-chat-app-e1f26.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}